In [3]:
import numpy
numpy.__version__

'1.16.4'

In [6]:
import numpy as np
nplist = np.array([1, 2, 3, 4])
nplist = nplist*2
print(nplist)

[2 4 6 8]


In [11]:
list1 = []
nplist1 = np.zeros(list1)
nplist2 = np.ones(list1)
nplist3 = np.empty(list1)
print(nplist1)
print(nplist2)
print(nplist3)

0.0
1.0
5.831091427420315e+252


In [18]:
nplist = np.arange(0, 20 ,2)
nplist

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
dimensions = np.zeros((3,3))
dimensions

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
dimensions.ndim

2

In [24]:
dimensions.shape

(3, 3)

In [25]:
dimensions.dtype

dtype('float64')

In [28]:
dimensions.reshape(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

ASSIGNMENT: shaw shank,
beautiful soap(scraping),
git